name: Go
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download modules
        run: go mod download

      - name: Run tests
        shell: bash
        run: make test
